version: "3.8"
services:
  rstudio:
    image: r410bioc313
    container_name: rprot
    working_dir: /home/rstudio/rproject
    build:
      context: docker
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=pw
      - DISABLE_AUTH=true
    volumes:
      - .:${CONTAINER:-/home/rstudio/rproject}